package CalculatorApp;


/**
* CalculatorApp/CalculatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, March 30, 2025 10:28:57 AM UTC
*/

public interface CalculatorOperations 
{
  float add (float a, float b);
  float subtract (float a, float b);
  float multiply (float a, float b);
  float divide (float a, float b);
} // interface CalculatorOperations
