package CalculatorApp;


/**
* CalculatorApp/Calculator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculator.idl
* Sunday, March 30, 2025 10:28:57 AM UTC
*/

public interface Calculator extends CalculatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calculator
