package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Sunday, March 30, 2025 11:05:00 AM UTC
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
